# Generated by Django 5.1.4 on 2024-12-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('OS', 'On-Site'), ('RT', 'Remote')], default='FT', max_length=2)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('last_date_to_apply', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
