# Generated by Django 5.1.4 on 2024-12-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('OS', 'On-Site'), ('RT', 'Remote')], max_length=2)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.ManyToManyField(to='jobPost.jobtype'),
        ),
    ]
