# Generated by Django 5.1.4 on 2024-12-28 17:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPost', '0002_jobtype_remove_jobpost_job_type_jobpost_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('OS', 'On-Site'), ('RT', 'Remote')], default=['FT'], max_length=17),
        ),
    ]
