# Generated by Django 5.1.4 on 2024-12-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('jobPost', '0003_remove_jobpost_job_type_delete_jobtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Categories',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='Categories.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('OS', 'On-Site'), ('RT', 'Remote')], default='FT', max_length=2),
        ),
    ]
