# Generated by Django 5.1.4 on 2024-12-29 14:02

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('jobPost', '0004_remove_jobpost_requirements_jobpost_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='last_date_to_apply',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='Categories',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('OS', 'On-Site'), ('RT', 'Remote')], max_length=17),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='Categories',
            field=models.ManyToManyField(to='Categories.categories'),
        ),
    ]
