# Generated by Django 5.1.4 on 2024-12-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPost', '0009_remove_notification_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Find', 'Find'), ('Not-Find', 'Not-Find')], default='Not-Find', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='jobPost.application'),
            preserve_default=False,
        ),
    ]
