# Generated by Django 5.1.4 on 2025-01-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPost', '0010_jobpost_status_notification_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='Categories',
            new_name='Required_Technical_Skills',
        ),
    ]
